theme: jekyll-theme-cayman
 
# Setup
title:        krnl
description: key bypasser
google_analytics: [""]
baseurl:      ""
paginate:     1
values:
layout: single

#Others
markdown: kramdown  

include: ["_pages"]